### ISSUE TITLE
Deploy pull request changes to a public url

### ISSUE THREAD

**Issue by thatguynamedandy** [BrandwatchLtd/axiom#110]
In order that we can be sure we are happy with a feature before merging it we should be able to preview it, ideally without the hassle of pulling down forks off different branches.

We should look at trying to deploy pull requests onto Github pages, potentially under a sub directory. We should then be sure any sub directories are cleaned up once a branch is merged/closed.

**Comment by siggysamson** [comment]
That's something we definitely should be working on! I ran into exactly this issue with my recent PR.

I like the idea of using Github Pages for it because that's the easiest to use solution. Some thoughts around this:
- When I was setting up the deploy to Github Pages I ran into a couple issues with the base url so I'm not sure if we might experience issues because we are going to store everything in a subdirectory. I _think_ we should be able to solve this by adding the proper publicPath though so might not be an issue any more.
- We should always make sure that the top level dir contains the latest from master.
- Webhooks should help us detecting closed PRs so removing already deployed branches should be possible

**Comment by HHogg** [comment]
> When I was setting up the deploy to Github Pages I ran into a couple issues with the base url

This also relates to #90, I have a WIP branch at the moment to remove the basepath... I didn't realise it has an evil side to it that causes all sorts of mayhem 😸

**Comment by thatguynamedandy** [comment]
I've come close to getting the first part done with this commit...
https://github.com/thatguynamedandy/axiom/commit/090c5d96175919363aac62bf67b6951f5af6af2b

The idea is that branches are just deployed to a sub directory, it works, however there is one problem. The `gh-pages` module has an `add` command, this needs to be set to prevent the master deploy deleting all of the branch deploys, sadly though it means any removed files will remain on the branch. There doesn't appear to be way currently to get around it, which leads to the following set of options...

- Create a PR into gh-pages which helps to cover our use case
- Live with the fact that there will be orphaned files in the gh-pages branch
- Use something else altogether https://surge.sh/ seems to have gained some traction

**Comment by thatguynamedandy** [comment]
https://stackshare.io/stackups/github-pages-vs-surge-vs-netlify

**Comment by siggysamson** [comment]
Regarding the orphaned files: Could we come up with a script that runs whenever the master branch is build to compare the directories against the set of open PRs?

- Send a request to GH API
- Get a list of all open PRs
- Compare against folders in `pull-request`
- Delete the ones that don't match.

For now we could just live with orphaned files and clean it up occasionally.

On a more general note: When we are doing this we should make sure the build is only done for maintainers. As I think this could be misused by others to just host random stuff. Not sure if that's a valid concern but definitely something to keep in mind

**Comment by thatguynamedandy** [comment]
I had considered that approach, but I think there might a few too many manual steps, when an out of the box solution might do it for us. I quite like the look of the netlify github integration..

https://github.com/integrations/netlify

It appears to run as a status check, my assumption is that it hopefully tear it down when the PR is merged, thus saving a lot of hassle. I would hope that only deploying PRs would help with the misuse as we could just close any dubious looking PRs, it is something to keep aware of though.

**Comment by siggysamson** [comment]
I agree actually - too much overhead if we could just use a service instead. Netlify looks great - I think we should go ahead and try it (we can always switch to something else if we aren't satisfied)

**Comment by HHogg** [comment]
Closing this as we now have a process in place for deploying via Netlify. See contributing doc.
