### ISSUE TITLE
Allow for prop type manipulation in the examples view

### ISSUE THREAD

**Issue by thatguynamedandy** [BrandwatchLtd/axiom#151]
I've always been a big fan of using something like dat-gui for development..

https://workshop.chromeexperiments.com/examples/gui

It allows you to tweak the properties of an element on the page and see the affect straight away. I was wondering if we should contemplate rolling our own PropTypes editor that programatically renders all of the available prop types and lets the user interact with them. This way our demo pages could be slightly more interactive and allow users to test the different variants. It may be suited to a standalone repo as it may have other external uses.

![screen shot 2017-04-11 at 09 27 41](https://cloud.githubusercontent.com/assets/2196085/24899717/322f6098-1e99-11e7-89a7-4b4bd8ff765f.png)

**Comment by HHogg** [comment]
Note: [The way Shopify do it](https://polaris.shopify.com/components/images-and-icons/badge#examples)

**Comment by HHogg** [comment]
Should be resolved by #245

**Comment by HHogg** [comment]
Closing as Axiom now has the capability
