### ISSUE TITLE
Dialog component always returns "null"

### ISSUE THREAD

**Issue by siggysamson** [BrandwatchLtd/axiom#342]
Hey all,

we've been testing out Axiom in another environment and came across an issue with the `Dialog`-component. I'm raising this ticket as we currently don't have enough time to investigate it further. On the [Axiom website](https://brandwatchltd.github.io/axiom/docs/components/dialog) the dialog component is working fine but from looking at the test snapshot it indicates there might indeed be a problem with it:
https://github.com/BrandwatchLtd/axiom/commit/c0181de60883db9b6dc6f05cc15962fb4d38152e#diff-b0595b317df475dc4c82f1cc852bcbc8

When using the following code we always get `null` returned. It looks like the problem _might_ be in the SubTree component as this is the only one returning `null` in a condition but I'm not sure why. Maybe the `children` property isn't passed on at some point.
Any other Axiom components are working just fine

```javascript
const component = () => (
  <Dialog fullscreen={false} isOpen={true} onRequestClose={() => { console.log('close'); }}>
    <DialogHeader onRequestClose={() => {}}>Dialog Header</DialogHeader>
      <DialogBody>
        <TextInput disabled={true} invalid={false} value="" label="Name" />
        <TextArea height={100} label="Your message:" defaultValue="" />
      </DialogBody>
    <DialogFooter>
      <ButtonGroup joined={false}>
        <Button>Submit</Button>
        <Button style="secondary">Cancel</Button>
      </ButtonGroup>
   </DialogFooter>
  </Dialog>
);
```

Sorry for just dropping this here, happy to provide you with any more details you might need! The issue occurred with Axiom v25.7.3

**Comment by HHogg** [comment]
Hey @siggysamson, thanks for logging. Odd as it may be, the snapshot tests are correct. The `<SubTree>` component renders content provided in the `subtree()` prop within it's own React app outside the context of the app that has called it.... but it _can_ also `render()` it's given children. 

For example the `<Position>` component, renders a similar subtree app (defined inside `<PositionContent>`) but it also renders children given to `<PositionTarget>` so a snapshot test of this would only show the  `<PositionTarget>` children. 

The `<Dialog>` component doesn't have a need for any target content like `<Position>` does. 

I've used the code provide above and the Dialog does appear to render correctly. Please let me know if this doesn't make sense and I'll try to do a better job of explaining it :D

**Comment by s-e-b** [comment]
Just FYI: I made some progress on this and the problem is definitely on our end... 

1. The `<SubTree>` component is appended to the body instead of our axiom wrapper element. That's why our wrapper only contained `react-empty`.

2. As we prefix all axiom classes with our `.ax-wrapper` class (which we currently set on the wrapper element  *only*) they didn't get applied at all - causing the actual `<Dialog>` to be invisible.

**Comment by siggysamson** [comment]
We've missed to add a `context`: https://github.com/BrandwatchLtd/axiom/blob/master/src/components/subtree/Subtree.js#L16

Thanks for your help @HHogg!
