### ISSUE TITLE
Tooltip arrow position is initially wrong

### ISSUE THREAD

**Issue by stefanbuck** [BrandwatchLtd/axiom#394]
The position of the arrow is initially wrong. However a little scroll fixes it. I noticed this behaviour in our application and after some investigation I found out that it behaves the same on the Axiom docs. 

![demo](https://user-images.githubusercontent.com/1393946/31809749-5b70fdc8-b579-11e7-96e9-24d1492edb82.gif)

**Comment by SeaOfTea** [comment]
I noticed this as well. I assumed it was an implementation error on our side. Except for it fixes on mouse movement.
![oct-20-2017 10-58-10](https://user-images.githubusercontent.com/3051921/31815760-9a38b97c-b585-11e7-9670-bf2215d3ac12.gif)
