### ISSUE TITLE
CSS Classes in Axiom components

### ISSUE THREAD

**Issue by kamilio** [BrandwatchLtd/axiom#585]
...

**Comment by lpoulter** [comment]
Would be interested if anyone has any thoughts on this issue? For me I think it's impossible to create a framework to cater for all use cases and allowing CSS classes provides an escape hatch to avoid getting blocked.

**Comment by lpoulter** [comment]
I think the React team themsleves have used these sort of escape hatches to great affect.

**Comment by ahume** [comment]
Closing this in favour of AX-11.

**Comment by lpoulter** [comment]
https://office.brandwatch.com/jira/browse/AX-11
