### ISSUE TITLE
Theme does not change color of heading

### ISSUE THREAD

**Issue by kamilio** [BrandwatchLtd/axiom#62]
Hello people, I was trying to change the color of the heading and it didn't really work out.

Could you help somebody?

```jsx
            <Heading theme="dark">YOOO</Heading>
            <Base theme="dark">
                <Heading>YO</Heading>
            </Base>
```

Cheers,

Kamil

![brandwatch___axiom](https://cloud.githubusercontent.com/assets/1078185/22158164/4614c7bc-df3b-11e6-9560-ad67ae5bdc5a.png)

**Comment by kamilio** [comment]
I am getting this error 
```
warning.js:36Warning: Unknown prop `text-disabled` on <h4> tag. Remove this prop from the element.
```

**Comment by HHogg** [comment]
@kamilio 😄 apologies I confused my example with the actual CSS classes... it follows the React standard of using cameCase. Ignore my hyphenated example...


```jsx
<Heading 
  textSubtle={ true }
  textDisabled={ true }
  textInvalid={ true }
  textValid={ true } />
```
