### ISSUE TITLE
HTTPS GCP CDN 

### ISSUE THREAD

**Issue by jdelight** [BrandwatchLtd/axiom#95]
Would be great to have a https version of the compiled CSS.

**Comment by HHogg** [comment]
cc @ahume as I remember Andy saying something was up/needed with GCP to get https working.

**Comment by ahume** [comment]
Doable, much more easily than when we first looked at this, as GCE now support having a storage bucket as a load balancer backend.

@jdelight You are using this for Facebook? What date would you need that?

**Comment by jdelight** [comment]
@ahume not urgent for me really was using it for a funky friday type project.

**Comment by ahume** [comment]
I don't think there's a current supported use-case for this. May come up again in the longer-term.
